### ISSUE TITLE
bundle exec not working

### ISSUE THREAD

**Issue by Wooody82** [kainio/solidus_multi_vendor#1]
Hi,
I tried to run "bundle exec bin/rails g solidus_multi_vendor:install" but i got this error.. any way to fix it? Thanks 

Running Rails from: /Development/App/solidus/sandbox
Traceback (most recent call last):
	3: from bin/rails:3:in `<main>'
	2: from bin/rails:3:in `require_relative'
	1: from /Development/App/solidus/sandbox/config/boot.rb:4:in `<top (required)>'
/Development/App/solidus/sandbox/config/boot.rb:4:in `require': cannot load such file -- bootsnap/setup (LoadError)

**Comment by kainio** [comment]
@malasaad82 This extension is still on active development, I migrated the extension to use solidus_dev_support I think that it's working fine, but unfortunately there's still some failing tests.

**Comment by rsmithlal** [comment]
@kainio, what's the status of this repository? Have you been actively working on it since this thread was opened? I'm looking to create or use some sort of multi-vendor system for solidus, and it might be good to get in touch and talk more about your efforts.

**Comment by an280420** [comment]
Hi @kainio. I tried run `bundle` but i got :
```
Could not find gem 'solidus_multi_vendor' in rubygems repository https://rubygems.org/ or installed locally.
The source does not contain any versions of 'solidus_multi_vendor'
```
Is there any other way to try this gem? Thanks

**Comment by an280420** [comment]
I solved this problem:
Edit your Gemfile :
```
gem 'solidus_multi_vendor', github: 'kainio/solidus_multi_vendor'
```
